title = "DQN config"

lr=0.0005
update_freq=10 
gamma=0.9 
epsilon=1
epsilon_decay=0.999
epsilon_min=0.01
replay_size=100 
target_update=10 

n_hidden=64 

replay_buffer_eps=1000
episodes_without_training=1000 

# Randomly assign passenger to cab
# Allows training in single-agent environment 
# and deployment in multi-agent enviroment
assign_psng=true

# Minimum requirement to add episode to replay memory
min_pick_ups=1 

# Configuration needed for munchausen
munchhausen=false 
entropy_tau=0.03 
alpha=0.9

