title = "Multi-Agent DQN config"

lr=0.001 
update_freq=10 
gamma=0.9 
epsilon=1
epsilon_decay=0.995 
epsilon_min=0.01
replay_size= 100 
target_update= 50 
n_hidden= 64 
episodes_without_training= 100 
replay_buffer_eps= 100
munchhausen= true 
min_pick_ups=1 
entropy_tau=0.03 
alpha=0.9
common_reward=false
assign_factor=2
assign_psng=false 
info=false
adv=true


# Adv configurations
adv_lr=0.01
adv_epsilon= 1
adv_replay_size= 10
adv_epsilon_decay= 0.995
adv_epsilon_min= 0.01
episodes_adv= 100
adv_eps_without_training= 100
adv_memory_size= 5000
n_msg= 2 
decentralized= false